server.port=0
spring.application.name=warehouse-service
spring.threads.virtual.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5433/warehouse_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Włączenie wsparcia Circuit Breakera w Feignie
spring.cloud.openfeign.circuitbreaker.enabled=true

# Konfiguracja specyficzna dla instancji o nazwie "product-service"
# Wielkość okna pomiarowego (pamięta 10 ostatnich strzałów)
resilience4j.circuitbreaker.instances.product-service.sliding-window-size=10
# Minimalna liczba strzałów, zanim zacznie w ogóle liczyć błędy
resilience4j.circuitbreaker.instances.product-service.minimum-number-of-calls=4
# Jeśli 50% z tych zapytań się wywali, Circuit Breaker się otwiera (aktywuje fallback)
resilience4j.circuitbreaker.instances.product-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.product-service.wait-duration-in-open-state=15s
resilience4j.circuitbreaker.instances.product-service.permitted-number-of-calls-in-half-open-state=3